spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: SamsungS261!@
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
        default_schema: public

    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE